### ISSUE TITLE
错别字汇总

### ISSUE THREAD

**Issue by JerryX** [liushooter/UsaVsUsa#2]
目前阅读到了第三章，这里列出目前在阅读过程中遇到的错字、别字。

**Comment by JerryX** [comment]
### 序言部分
1. "一百五十年前，马克思和恩格斯就在《共产党宣言》中宣布..." 一段
`但历史唯物主义指示的人类社会犮展规律，需要历史条件的成熟`，此处应该是"发展规律"

2. "越是深入地研究美国，越是摆脱了浮光掠影的图景" 一段的最后
`不同国家之间不可能筒单模仿`，此处应该是"简单模仿"

3. "本书共有十一章，我想在这里扼要点明一下"一段，其中的 (1)
`社会不均衡发及其诸特点`，此处少了一个"展"字

4. "第一：本书所涉及的面有限"一段
`不可能涵盖美国林林总总。的各个层面`，此处多了个句号

**Comment by JerryX** [comment]
### 第一章
**曼哈顿和唐人街**

1. "需要加以分析的是"一段
`这一现实，给人们最大的思维挑战`，按我的理解，应该在"给"字前面增加一个"是"字

**高度的商品化**

2. "现代人类牡会的发展"一段
`如果政治和行政系统由于结构和功能的制約`，应替换为简体的"约"字

**边远地区**

3. "亚美尼亚人的生活方式也很奇特"一段
`他们自己大约并不清楚世界上发生了并什么`，此处应该删掉"并"字

**阿马拿移民地**

4. "早期阿马拿的宪章规定社团的目标是"一段
`我们的在这里集体许诺`，此处的"的"字是否要改成"得"
`这个团体最初的集体主义实在一种宗教精神的鼓舞下形成的`，此处的"实"字应该是要换成"是"，猜测是作者笔误

**乡土景观**

5. '农业地区商品经济不那么发达'一段
`不入大城市里的人那样开化`，此处的"入"字，应该是要改成"如"

6. "乡村地区的生活水准不如城市"一段
`有少数地方几位贫穷`，这里的"位"应该改为"乎"

**Comment by JerryX** [comment]
### 第二章

**美国精神**

1. "康马杰认为美国人民精神的主要特点是什么呢"部分，下面的第三点
`讨厌琐碎的事务，、犹豫不决和胆小怕事`，此处的逗号应该拿掉

**五月花号**

2. "美国的建国历史陈列大部分集中在两个州"一段的最后
`都可视之力实物教科书`，此处的"力"字应该改为"为"

3. 下一段，"实物教科书的最初几章在麻萨诸塞州"一段
`他们会一本正经的向参 观者谈他们在海上的艰苦经历`，此处"参"和"观"之间的空格应删掉

4. “不过，有一点必须注意”一段
`这就是当时的土著——印第安人的文明程度不高`，这里的话，个人感觉，应该在"印第安人"后再增加一个破折号，两个破折号之间的词用于解释或者具体破折号之前的那个范围稍广的词"土著"

5. 最后一段，"任何社会想长治久安"一段的最后
`而传播的效果在很大程度上就取決于方法`，此处的"決"应替换为"决"

**政治信条**

6. "根据亨廷顿的观点"一段
`可以追溯到古代希腊，。`，此处应删掉逗号
`杜卡基斯和布什竞选中一个主要话题就是讨论何谓美国的主流`，"竞选中"后面增加一个"的"字应该会恰当一些

7. "亨廷顿认为在四个时期发生过这样的情形"一段
`亨廷顿认为在四个时期发生过这样的情形:革命时期`，此处半角冒号应替换为全角冒号

**二百年的宪法**

8. "另一重要的原因是宪法的自身变化"一段
`很难想象它能持到今天`，"持"字后面应该加个"续"字
`今无美国人对宪法的解释早已大于二百年前`，"无"字应改为"天"字

9. 最后一段，"关键的间题是"一段
`关键的间题是`，"间"字应改为"问"字

**政治基因**

10. "虽然是个小镇"一段
`已经印发了需要表決的事项`，此处的"決"字应替换为"决"

**政治规矩**

11. "1月20日早晨"一段
`相当的时闻`，其中的"闻"字应替换为"间"

12. “宣誓完毕”下的"呼吁振兴美国精神"一段
`美国如不其备崇高的道德目标`，其中的"其"字应该替换为"具"

**Comment by liushooter** [comment]
错别字已经修改  https://github.com/liushooter/UsaVsUsa/commit/4f1e3c5f29f386c40019d64daea16ceb83645747
